### PR TITLE
Profiling the cost of simulation as a function of agents simulated

### PR DESCRIPTION
**Pull request by rmm-fcul**
A basic test for how much the playground slows down under load of increasing number of bees and/or CASUs.

Note: this was developed prior to @plsm's fix for #56, so it uses an alternative method for computing the simulation time.  A future version should consider both measurement methods.

Note 2: this includes sample data from three different experiment series.  I wasn't totally sure whether data is OK in repository, but given that it a) provides a reference and b) illustrates how the plotter operates, I have included here.

Note 3: there isn't a "profiling" or "testing" branch in the main repo; the destination should probably not be the master branch, but I didn't see an option to go elsewhere.

### CODE REVIEW

**Comment by dmiklic** [comment]
To me, this does not really belong into the main repo. I'd rather put it into assisi/assisipy-examples

**Comment by rmm-fcul** [comment]
ok, sure.  I don't seem to have write access to the examples repo. I'm a
member of the assisi organisation, but maybe this isn't enough for access?

**Comment by dmiklic** [comment]
You should have access rights now.

**Comment by rmm-fcul** [comment]
done. (added to branch "profiling")

**Pull request closed without merging**
